// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MusiCoLab2.Models;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace MusiCoLab2.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20181205022322_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("MusiCoLab2.Modals.ProjectContributor", b =>
                {
                    b.Property<int>("ProjectId");

                    b.Property<int>("UserId");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectContributors");
                });

            modelBuilder.Entity("MusiCoLab2.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AudioUrl");

                    b.Property<string>("Comments");

                    b.Property<string>("Daw");

                    b.Property<string>("Instruments");

                    b.Property<bool>("IsPrivate");

                    b.Property<string>("Name");

                    b.Property<int?>("ProjectOwnerId");

                    b.Property<string>("Style");

                    b.HasKey("Id");

                    b.HasIndex("ProjectOwnerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("MusiCoLab2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Role");

                    b.Property<string>("Salt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MusiCoLab2.Modals.ProjectContributor", b =>
                {
                    b.HasOne("MusiCoLab2.Models.Project", "Project")
                        .WithMany("ProjectContributors")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MusiCoLab2.Models.User", "User")
                        .WithMany("ProjectContributors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MusiCoLab2.Models.Project", b =>
                {
                    b.HasOne("MusiCoLab2.Models.User", "ProjectOwner")
                        .WithMany()
                        .HasForeignKey("ProjectOwnerId");
                });
#pragma warning restore 612, 618
        }
    }
}
